//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fastforward.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class CareersEntities : DbContext
    {
        public CareersEntities()
            : base("name=CareersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ability> abilities { get; set; }
        public DbSet<content_model_reference> content_model_reference { get; set; }
        public DbSet<education_training_experience> education_training_experience { get; set; }
        public DbSet<ete_categories> ete_categories { get; set; }
        public DbSet<green_occupations> green_occupations { get; set; }
        public DbSet<green_task_statements> green_task_statements { get; set; }
        public DbSet<interest> interests { get; set; }
        public DbSet<job_zone_reference> job_zone_reference { get; set; }
        public DbSet<job_zones> job_zones { get; set; }
        public DbSet<knowledge> knowledges { get; set; }
        public DbSet<level_scale_anchors> level_scale_anchors { get; set; }
        public DbSet<occupation_data> occupation_data { get; set; }
        public DbSet<occupation_level_metadata> occupation_level_metadata { get; set; }
        public DbSet<scales_reference> scales_reference { get; set; }
        public DbSet<skill> skills { get; set; }
        public DbSet<survey_booklet_locations> survey_booklet_locations { get; set; }
        public DbSet<task_categories> task_categories { get; set; }
        public DbSet<task_ratings> task_ratings { get; set; }
        public DbSet<task_statements> task_statements { get; set; }
        public DbSet<tblCollegeStat> tblCollegeStats { get; set; }
        public DbSet<work_activities> work_activities { get; set; }
        public DbSet<work_context> work_context { get; set; }
        public DbSet<work_context_categories> work_context_categories { get; set; }
        public DbSet<work_styles> work_styles { get; set; }
        public DbSet<work_values> work_values { get; set; }
    
        public virtual ObjectResult<spGetCareerAbilities_Result> spGetCareerAbilities(string careerId)
        {
            var careerIdParameter = careerId != null ?
                new ObjectParameter("careerId", careerId) :
                new ObjectParameter("careerId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCareerAbilities_Result>("spGetCareerAbilities", careerIdParameter);
        }
    
        public virtual ObjectResult<spGetCareerById_Result> spGetCareerById(string careerId)
        {
            var careerIdParameter = careerId != null ?
                new ObjectParameter("careerId", careerId) :
                new ObjectParameter("careerId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCareerById_Result>("spGetCareerById", careerIdParameter);
        }
    
        public virtual ObjectResult<spGetCareerInfo_Result> spGetCareerInfo(string careerId)
        {
            var careerIdParameter = careerId != null ?
                new ObjectParameter("careerId", careerId) :
                new ObjectParameter("careerId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCareerInfo_Result>("spGetCareerInfo", careerIdParameter);
        }
    
        public virtual ObjectResult<spGetCareerInterests_Result> spGetCareerInterests(string careerId)
        {
            var careerIdParameter = careerId != null ?
                new ObjectParameter("careerId", careerId) :
                new ObjectParameter("careerId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCareerInterests_Result>("spGetCareerInterests", careerIdParameter);
        }
    
        public virtual ObjectResult<spGetCareerKnowledge_Result> spGetCareerKnowledge(string careerId)
        {
            var careerIdParameter = careerId != null ?
                new ObjectParameter("careerId", careerId) :
                new ObjectParameter("careerId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCareerKnowledge_Result>("spGetCareerKnowledge", careerIdParameter);
        }
    
        public virtual ObjectResult<spGetCareerListByName_Result> spGetCareerListByName(string careerName)
        {
            var careerNameParameter = careerName != null ?
                new ObjectParameter("careerName", careerName) :
                new ObjectParameter("careerName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCareerListByName_Result>("spGetCareerListByName", careerNameParameter);
        }
    
        public virtual ObjectResult<spGetCareerSkills_Result> spGetCareerSkills(string careerId)
        {
            var careerIdParameter = careerId != null ?
                new ObjectParameter("careerId", careerId) :
                new ObjectParameter("careerId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCareerSkills_Result>("spGetCareerSkills", careerIdParameter);
        }
    
        public virtual ObjectResult<spGetCareerTasks_Result> spGetCareerTasks(string careerId)
        {
            var careerIdParameter = careerId != null ?
                new ObjectParameter("careerId", careerId) :
                new ObjectParameter("careerId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCareerTasks_Result>("spGetCareerTasks", careerIdParameter);
        }
    
        public virtual ObjectResult<spGetCareerWorkActivities_Result> spGetCareerWorkActivities(string careerId)
        {
            var careerIdParameter = careerId != null ?
                new ObjectParameter("careerId", careerId) :
                new ObjectParameter("careerId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCareerWorkActivities_Result>("spGetCareerWorkActivities", careerIdParameter);
        }
    
        public virtual ObjectResult<spGetCareerWorkStyles_Result> spGetCareerWorkStyles(string careerId)
        {
            var careerIdParameter = careerId != null ?
                new ObjectParameter("careerId", careerId) :
                new ObjectParameter("careerId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCareerWorkStyles_Result>("spGetCareerWorkStyles", careerIdParameter);
        }
    
        public virtual ObjectResult<spGetCareerWorkValues_Result> spGetCareerWorkValues(string careerId)
        {
            var careerIdParameter = careerId != null ?
                new ObjectParameter("careerId", careerId) :
                new ObjectParameter("careerId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCareerWorkValues_Result>("spGetCareerWorkValues", careerIdParameter);
        }
    
        public virtual ObjectResult<spGetJobZone_Result> spGetJobZone(string careerId)
        {
            var careerIdParameter = careerId != null ?
                new ObjectParameter("careerId", careerId) :
                new ObjectParameter("careerId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetJobZone_Result>("spGetJobZone", careerIdParameter);
        }
    
        public virtual ObjectResult<spGetCareerInfoBasic_Result> spGetCareerInfoBasic(string careerId)
        {
            var careerIdParameter = careerId != null ?
                new ObjectParameter("careerId", careerId) :
                new ObjectParameter("careerId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCareerInfoBasic_Result>("spGetCareerInfoBasic", careerIdParameter);
        }
    
        public virtual ObjectResult<spGetCareerInfoAbilities_Result> spGetCareerInfoAbilities(string careerId)
        {
            var careerIdParameter = careerId != null ?
                new ObjectParameter("careerId", careerId) :
                new ObjectParameter("careerId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCareerInfoAbilities_Result>("spGetCareerInfoAbilities", careerIdParameter);
        }
    
        public virtual ObjectResult<spGetCareerInfoCareerTasks_Result> spGetCareerInfoCareerTasks(string careerId)
        {
            var careerIdParameter = careerId != null ?
                new ObjectParameter("careerId", careerId) :
                new ObjectParameter("careerId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCareerInfoCareerTasks_Result>("spGetCareerInfoCareerTasks", careerIdParameter);
        }
    
        public virtual ObjectResult<spGetCareerInfoInterests_Result> spGetCareerInfoInterests(string careerId)
        {
            var careerIdParameter = careerId != null ?
                new ObjectParameter("careerId", careerId) :
                new ObjectParameter("careerId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCareerInfoInterests_Result>("spGetCareerInfoInterests", careerIdParameter);
        }
    
        public virtual ObjectResult<spGetCareerInfoJobZone_Result> spGetCareerInfoJobZone(string careerId)
        {
            var careerIdParameter = careerId != null ?
                new ObjectParameter("careerId", careerId) :
                new ObjectParameter("careerId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCareerInfoJobZone_Result>("spGetCareerInfoJobZone", careerIdParameter);
        }
    
        public virtual ObjectResult<spGetCareerInfoKnowledge_Result> spGetCareerInfoKnowledge(string careerId)
        {
            var careerIdParameter = careerId != null ?
                new ObjectParameter("careerId", careerId) :
                new ObjectParameter("careerId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCareerInfoKnowledge_Result>("spGetCareerInfoKnowledge", careerIdParameter);
        }
    
        public virtual ObjectResult<spGetCareerInfoSkills_Result> spGetCareerInfoSkills(string careerId)
        {
            var careerIdParameter = careerId != null ?
                new ObjectParameter("careerId", careerId) :
                new ObjectParameter("careerId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCareerInfoSkills_Result>("spGetCareerInfoSkills", careerIdParameter);
        }
    
        public virtual ObjectResult<spGetCareerInfoWorkActivities_Result> spGetCareerInfoWorkActivities(string careerId)
        {
            var careerIdParameter = careerId != null ?
                new ObjectParameter("careerId", careerId) :
                new ObjectParameter("careerId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCareerInfoWorkActivities_Result>("spGetCareerInfoWorkActivities", careerIdParameter);
        }
    
        public virtual ObjectResult<spGetCareerInfoWorkStyles_Result> spGetCareerInfoWorkStyles(string careerId)
        {
            var careerIdParameter = careerId != null ?
                new ObjectParameter("careerId", careerId) :
                new ObjectParameter("careerId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCareerInfoWorkStyles_Result>("spGetCareerInfoWorkStyles", careerIdParameter);
        }
    
        public virtual ObjectResult<spGetCareerInfoWorkValues_Result> spGetCareerInfoWorkValues(string careerId)
        {
            var careerIdParameter = careerId != null ?
                new ObjectParameter("careerId", careerId) :
                new ObjectParameter("careerId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCareerInfoWorkValues_Result>("spGetCareerInfoWorkValues", careerIdParameter);
        }
    }
}
