//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fastforward.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ete_categories
    {
        public ete_categories()
        {
            this.education_training_experience = new HashSet<education_training_experience>();
        }
    
        public string element_id { get; set; }
        public string scale_id { get; set; }
        public decimal category { get; set; }
        public string category_description { get; set; }
    
        public virtual content_model_reference content_model_reference { get; set; }
        public virtual ICollection<education_training_experience> education_training_experience { get; set; }
        public virtual scales_reference scales_reference { get; set; }
    }
}
