//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fastforward.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class occupation_data
    {
        public occupation_data()
        {
            this.abilities = new HashSet<ability>();
            this.education_training_experience = new HashSet<education_training_experience>();
            this.green_occupations = new HashSet<green_occupations>();
            this.green_task_statements = new HashSet<green_task_statements>();
            this.interests = new HashSet<interest>();
            this.job_zones = new HashSet<job_zones>();
            this.knowledges = new HashSet<knowledge>();
            this.occupation_level_metadata = new HashSet<occupation_level_metadata>();
            this.skills = new HashSet<skill>();
            this.task_ratings = new HashSet<task_ratings>();
            this.task_statements = new HashSet<task_statements>();
            this.work_activities = new HashSet<work_activities>();
            this.work_context = new HashSet<work_context>();
            this.work_styles = new HashSet<work_styles>();
            this.work_values = new HashSet<work_values>();
        }
    
        public string onetsoc_code { get; set; }
        public string title { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<ability> abilities { get; set; }
        public virtual ICollection<education_training_experience> education_training_experience { get; set; }
        public virtual ICollection<green_occupations> green_occupations { get; set; }
        public virtual ICollection<green_task_statements> green_task_statements { get; set; }
        public virtual ICollection<interest> interests { get; set; }
        public virtual ICollection<job_zones> job_zones { get; set; }
        public virtual ICollection<knowledge> knowledges { get; set; }
        public virtual ICollection<occupation_level_metadata> occupation_level_metadata { get; set; }
        public virtual ICollection<skill> skills { get; set; }
        public virtual ICollection<task_ratings> task_ratings { get; set; }
        public virtual ICollection<task_statements> task_statements { get; set; }
        public virtual ICollection<work_activities> work_activities { get; set; }
        public virtual ICollection<work_context> work_context { get; set; }
        public virtual ICollection<work_styles> work_styles { get; set; }
        public virtual ICollection<work_values> work_values { get; set; }
    }
}
