//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fastforward.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class task_statements
    {
        public task_statements()
        {
            this.green_task_statements = new HashSet<green_task_statements>();
            this.task_ratings = new HashSet<task_ratings>();
        }
    
        public string onetsoc_code { get; set; }
        public decimal task_id { get; set; }
        public string task { get; set; }
        public string task_type { get; set; }
        public Nullable<decimal> incumbents_responding { get; set; }
        public System.DateTime date_updated { get; set; }
        public string domain_source { get; set; }
    
        public virtual ICollection<green_task_statements> green_task_statements { get; set; }
        public virtual occupation_data occupation_data { get; set; }
        public virtual ICollection<task_ratings> task_ratings { get; set; }
    }
}
