//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fastforward.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class task_categories
    {
        public task_categories()
        {
            this.task_ratings = new HashSet<task_ratings>();
        }
    
        public string scale_id { get; set; }
        public decimal category { get; set; }
        public string category_description { get; set; }
    
        public virtual scales_reference scales_reference { get; set; }
        public virtual ICollection<task_ratings> task_ratings { get; set; }
    }
}
