//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fastforward.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCollegeStat
    {
        public long CollegeID { get; set; }
        public Nullable<int> Founded { get; set; }
        public string Setting { get; set; }
        public Nullable<int> TotalUndergrads { get; set; }
        public Nullable<int> TotalGradStudents { get; set; }
        public string TuitionInState { get; set; }
        public string TuitionOutState { get; set; }
        public string Process { get; set; }
        public Nullable<System.DateTime> ProcessDeadLine { get; set; }
        public Nullable<System.DateTime> RegularAppDeadline { get; set; }
        public string SelectivityRating { get; set; }
        public string MailAddress { get; set; }
        public string AdmissionsOfficeAddress { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string SchoolType { get; set; }
        public string OtherDesignations { get; set; }
        public string AcademicCalendar { get; set; }
        public string Distance { get; set; }
        public string Size { get; set; }
        public string ReligiousAffiliation { get; set; }
        public string Diversity { get; set; }
        public string PoliticalLeaning { get; set; }
        public string PoliticalActivity { get; set; }
        public string GenderBalance { get; set; }
        public string CoreCurriculumReq { get; set; }
        public string SportsScene { get; set; }
        public string GreekLife { get; set; }
        public string ArtsScene { get; set; }
        public string AcademicScene { get; set; }
        public string SingleSex { get; set; }
        public string HistoricallyBlack { get; set; }
        public string GayFriendly { get; set; }
        public Nullable<int> TotalEnrollment { get; set; }
        public Nullable<decimal> StudentsStatesPercentage { get; set; }
        public Nullable<decimal> StudentsGenderPercentage { get; set; }
        public Nullable<decimal> StudentNativePercentage { get; set; }
        public Nullable<decimal> StudentAsianPacificPercentage { get; set; }
        public Nullable<decimal> StudentBlackNonHispanicPercentage { get; set; }
        public Nullable<decimal> StudentHispanicPercentage { get; set; }
        public Nullable<decimal> StudentWhiteNonHispanicPercentage { get; set; }
        public Nullable<decimal> ApplicantsAdmitPercentage { get; set; }
        public Nullable<decimal> ApplicantsAdmitEarlyPercentage { get; set; }
        public Nullable<decimal> TransferAcceptancePercentage { get; set; }
        public Nullable<decimal> TopTenHSStudentPercentage { get; set; }
        public Nullable<decimal> TopQuarterHSStudentPercentage { get; set; }
        public Nullable<decimal> TopHalfHSStudentPercentage { get; set; }
        public string SATRange { get; set; }
        public string ACTRange { get; set; }
        public string GPARange { get; set; }
        public Nullable<System.DateTime> ProcessNotification { get; set; }
        public Nullable<System.DateTime> RegularAppNotification { get; set; }
        public Nullable<System.DateTime> FinancialAidDeadline { get; set; }
        public Nullable<System.DateTime> TransferAppDeadline { get; set; }
        public Nullable<System.DateTime> TransferAppNotification { get; set; }
        public string Other { get; set; }
        public Nullable<bool> IsCampusHousingGuaranteed { get; set; }
        public Nullable<decimal> LiveInFirstYearPercentage { get; set; }
        public Nullable<decimal> MenInFraternitlesPercentage { get; set; }
        public Nullable<decimal> WomenInSororitiesPercentage { get; set; }
        public System.DateTime dbCreated { get; set; }
        public string Region { get; set; }
        public string State { get; set; }
        public Nullable<decimal> ApplicationFee { get; set; }
        public string AdmittedWhoEnroll { get; set; }
        public string City { get; set; }
        public string CEEEBCode { get; set; }
        public string ACTCode { get; set; }
        public Nullable<int> NumberOfOrgs { get; set; }
        public Nullable<int> NumberOfFraternities { get; set; }
        public Nullable<int> NumberOfSororities { get; set; }
        public Nullable<decimal> PercentageFromOutOfState { get; set; }
        public Nullable<decimal> PercentageMen { get; set; }
        public string Mid50SATRead { get; set; }
        public string Mid50SATMath { get; set; }
        public string Mid50Writing { get; set; }
        public Nullable<bool> PartOfConsortium { get; set; }
        public Nullable<bool> Conservatory { get; set; }
        public Nullable<bool> CoOp { get; set; }
        public string AcademicRequirements { get; set; }
        public Nullable<bool> ForeignRequirement { get; set; }
        public Nullable<bool> WritingRequirement { get; set; }
        public Nullable<bool> NotIncludingWritingScore { get; set; }
        public Nullable<bool> NoApplicationFee { get; set; }
        public string SimilarColleges { get; set; }
        public Nullable<double> SATScoreLow { get; set; }
        public Nullable<double> SATScoreHigh { get; set; }
        public Nullable<double> ACTScoreLow { get; set; }
        public Nullable<double> ACTScoreHigh { get; set; }
        public Nullable<double> GPALow { get; set; }
        public Nullable<double> GPAHigh { get; set; }
        public string Core { get; set; }
        public Nullable<decimal> FeeBooksAndSupplies { get; set; }
        public Nullable<decimal> FeeOnCampusRoomAndBoard { get; set; }
        public Nullable<decimal> FeeTotalOnCampus { get; set; }
        public Nullable<decimal> FamilyIncome1 { get; set; }
        public Nullable<decimal> FamilyIncome2 { get; set; }
        public Nullable<decimal> FamilyIncome3 { get; set; }
        public Nullable<decimal> FamilyIncome4 { get; set; }
        public Nullable<decimal> FamilyIncome5 { get; set; }
        public Nullable<decimal> PercentageStudentsReceivingAnyFinancialAid { get; set; }
        public Nullable<decimal> PercentageStudentsReceivingFederalGrants { get; set; }
        public Nullable<decimal> PercentageStudentsReceivingInstitutionalGrantsorScholarships { get; set; }
        public Nullable<decimal> PercentageStudentsReceivingFederalLoans { get; set; }
        public Nullable<decimal> PercentageInternational { get; set; }
        public string Mid50ACTRead { get; set; }
        public string Mid50ACTMath { get; set; }
        public string Mid50ACTWriting { get; set; }
        public Nullable<int> FacultyTotalFullTime { get; set; }
        public string FacultyStudentFacultyRatio { get; set; }
    }
}
